name: py2
channels:
 - symengine/label/dev
 - conda-forge
 - defaults
dependencies:
 - pexpect
 - pytools
 - conda-forge::numpy
 - conda-forge::sympy
 - python=2.7
 - symengine/label/dev::python-symengine=0.3.0.rc0
 - maxima
