name: py3
channels:
 - symengine/label/dev
 - conda-forge
 - defaults
dependencies:
 - pexpect
 - conda-forge::numpy
 - conda-forge::sympy
 - python=3.5
 - symengine/label/dev::python-symengine=0.3.0.rc0
 - maxima
